
ex1 (x: a): b = x + 1u32

// This is a bug/limitation of the current system.
// This currently produces no type errors despite the type given being too general.
ex2: a -> b =
    fn x -> x

// args: --show-types
// expected exit status: 101
// expected stderr:
// thread 'main' panicked at src/type_inference/type_context.rs:122:58:
// not yet implemented: Resolve named types
// note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

